package com.miniqwerty.kb

import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader
import java.text.Normalizer

/**
 * Offline suggestion engine: accent-insensitive prefix completion plus
 * bigram-based next-word prediction, with a personal learning layer.
 *
 * Pure Kotlin — no Android imports (the [InputStream]s are plain JVM) — so it
 * stays unit-testable without instrumentation, like [TelexProcessor].
 *
 * Data model:
 *  - Word table: three parallel arrays (normalized key, display word, corpus
 *    frequency) sorted by normalized key. Loaded from the asset generated by
 *    `tools/generate_wordlist.py`. Lookup: binary-search the lower bound of
 *    the prefix, scan the matching range, keep top-k by score.
 *  - Bigram table: four parallel arrays (normalized prev, next display word,
 *    count) sorted by (prev, -count). Lookup: binary search the group, scan
 *    it, keep top-k by score.
 *  - Learning: a map of normalized word to (display word, commit count),
 *    fed by the IME on every committed word and persisted by the IME (this
 *    object stays stateless on disk). Learned words score `count * USER_BOOST`
 *    on top of any corpus frequency, so a word used even once outranks every
 *    corpus word on the same prefix — Gboard-like personal ranking.
 *
 * Normalization (the single source of truth on both sides of every lookup):
 * NFKD decompose, drop combining marks (U+0300..U+036F — tone marks,
 * breve/circumflex/horn, and the stroke of đ), then lowercase.
 */
object SuggestionEngine {

    /** Score multiplier for learned words: beats any corpus frequency
     *  (max corpus freq is ~500k), so count >= 1 wins a prefix match. */
    const val USER_BOOST = 1_000_000

    /** Hard cap on the learned-word set, enforced when serializing. */
    const val MAX_USER_WORDS = 5000

    /** First line of every backup file and of the prefs serialization. */
    const val BACKUP_HEADER_LINE = "#mini_qwerty_words_v1"

    // ── Word table ────────────────────────────────────────────────────────

    private var wordKeys: Array<String> = emptyArray()      // normalized, sorted
    private var wordDisplays: Array<String> = emptyArray()  // parallel
    private var wordFreqs: IntArray = IntArray(0)           // parallel
    private var wordsLoaded = false

    // ── Bigram table ──────────────────────────────────────────────────────

    private var bigramPrevs: Array<String> = emptyArray()   // normalized prev, sorted
    private var bigramNexts: Array<String> = emptyArray()   // parallel display word
    private var bigramCounts: IntArray = IntArray(0)        // parallel
    private var bigramsLoaded = false

    // ── Learning ──────────────────────────────────────────────────────────

    /** Normalized word → (display word, commit count). */
    private val userCounts = LinkedHashMap<String, Pair<String, Int>>()

    // ── Loading ───────────────────────────────────────────────────────────

    /** Load the word-frequency table (`word<TAB>freq` lines, UTF-8). */
    fun loadWords(stream: InputStream) {
        val entries = ArrayList<Pair<String, Pair<String, Int>>>()
        BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).useLines { lines ->
            for (line in lines) {
                val tab = line.indexOf('\t')
                if (tab <= 0) continue
                val word = line.substring(0, tab)
                val freq = line.substring(tab + 1).toIntOrNull() ?: continue
                val key = normalize(word)
                if (key.isEmpty()) continue
                entries.add(key to (word to freq))
            }
        }
        // Stable sort keeps file order (frequency-desc) for equal keys.
        entries.sortBy { it.first }
        wordKeys = Array(entries.size) { entries[it].first }
        wordDisplays = Array(entries.size) { entries[it].second.first }
        wordFreqs = IntArray(entries.size) { entries[it].second.second }
        wordsLoaded = true
    }

    /** Load the bigram table (`prev<TAB>next<TAB>count` lines, UTF-8). */
    fun loadBigrams(stream: InputStream) {
        val entries = ArrayList<Triple<String, String, Int>>()
        BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).useLines { lines ->
            for (line in lines) {
                val tabs = line.split('\t')
                if (tabs.size != 3) continue
                val key = normalize(tabs[0])
                val next = tabs[1]
                val count = tabs[2].toIntOrNull() ?: continue
                if (key.isEmpty() || normalize(next).isEmpty()) continue
                entries.add(Triple(key, next, count))
            }
        }
        // Sorted by (prev, -count): within a group the best pairs come first.
        entries.sortWith(compareBy({ it.first }, { -it.third }))
        bigramPrevs = Array(entries.size) { entries[it].first }
        bigramNexts = Array(entries.size) { entries[it].second }
        bigramCounts = IntArray(entries.size) { entries[it].third }
        bigramsLoaded = true
    }

    // ── Normalization ─────────────────────────────────────────────────────

    /** Strip diacritics and case: `Tôi` → `toi`, `nước` → `nuoc`, `đ` → `d`. */
    fun normalize(s: String): String {
        val decomposed = Normalizer.normalize(s, Normalizer.Form.NFKD)
        val sb = StringBuilder(decomposed.length)
        for (ch in decomposed) {
            if (ch.code in 0x0300..0x036F) continue  // combining marks
            sb.append(ch)
        }
        return sb.toString().lowercase()  // Kotlin lowercase() is locale-invariant
    }

    // ── Learning feed ─────────────────────────────────────────────────────

    /** Replace the learned-word map (used on restore and IME init). */
    fun setUserCounts(counts: Map<String, Pair<String, Int>>) {
        userCounts.clear()
        userCounts.putAll(counts)
    }

    /** Record one committed word, incrementing its count. */
    fun addUserWord(word: String) {
        val key = normalize(word)
        if (key.isEmpty()) return
        val existing = userCounts[key]
        userCounts[key] = if (existing == null) (word to 1) else (existing.first to existing.second + 1)
    }

    /** Live view of the learned words, keyed by normalized form. */
    fun userCountsSnapshot(): Map<String, Pair<String, Int>> = LinkedHashMap(userCounts)

    private fun userBoost(word: String): Int {
        val entry = userCounts[normalize(word)] ?: return 0
        return entry.second * USER_BOOST
    }

    // ── Lookups ───────────────────────────────────────────────────────────

    /**
     * Top [max] completions for a resolved composing word.
     *
     * Query is the Telex-resolved display form (callers resolve the raw
     * buffer first — see MiniKeyboardIME.updateComposingText). Matching is
     * accent-insensitive on both sides. The resolved word itself is never
     * returned (it occupies the center slot of the strip).
     */
    fun suggestions(resolved: String, max: Int = 2): List<String> {
        val query = normalize(resolved)
        if (!wordsLoaded || query.isEmpty()) return emptyList()

        data class Candidate(val word: String, val score: Int)

        val candidates = ArrayList<Candidate>()
        val seen = HashSet<String>()

        // Corpus prefix range.
        var i = lowerBound(wordKeys, query)
        while (i < wordKeys.size && wordKeys[i].startsWith(query)) {
            val word = wordDisplays[i]
            if (word != resolved && seen.add(word)) {
                candidates.add(Candidate(word, wordFreqs[i] + userBoost(word)))
            }
            i++
        }

        // Learned words missing from the corpus (names, slang, fresh terms).
        for ((key, entry) in userCounts) {
            if (key.startsWith(query) && entry.first != resolved && seen.add(entry.first)) {
                candidates.add(Candidate(entry.first, entry.second * USER_BOOST))
            }
        }

        candidates.sortByDescending { it.score }
        return candidates.take(max).map { it.word }
    }

    /**
     * Top [max] words most likely to follow [prev] (bigram table), with
     * learned words boosted. Empty when the previous word is unknown.
     */
    fun nextWords(prev: String, max: Int = 3): List<String> {
        val key = normalize(prev)
        if (!bigramsLoaded || key.isEmpty()) return emptyList()

        data class Candidate(val word: String, val score: Int)

        val candidates = ArrayList<Candidate>()
        val seen = HashSet<String>()

        var i = lowerBound(bigramPrevs, key)
        while (i < bigramPrevs.size && bigramPrevs[i] == key) {
            val word = bigramNexts[i]
            if (seen.add(word)) {
                candidates.add(Candidate(word, bigramCounts[i] + userBoost(word)))
            }
            i++
        }

        candidates.sortByDescending { it.score }
        return candidates.take(max).map { it.word }
    }

    // ── Backup format ─────────────────────────────────────────────────────

    /**
     * Serialize learned words for backup/sharing:
     * header line, then `word<TAB>count` sorted by (-count, word), capped at
     * [MAX_USER_WORDS] (lowest counts dropped).
     */
    fun serializeUserCounts(counts: Map<String, Pair<String, Int>>): String {
        val ordered = counts.values.sortedWith(compareBy({ -it.second }, { it.first }))
            .take(MAX_USER_WORDS)
        val sb = StringBuilder()
        sb.append(BACKUP_HEADER_LINE).append('\n')
        for ((word, count) in ordered) {
            sb.append(word).append('\t').append(count).append('\n')
        }
        return sb.toString()
    }

    /**
     * Parse a backup/restore file or the prefs string. Header lines are
     * skipped; malformed lines are dropped. Returns empty map on garbage.
     */
    fun parseUserCounts(raw: String?): Map<String, Pair<String, Int>> {
        if (raw.isNullOrBlank()) return emptyMap()
        val counts = LinkedHashMap<String, Pair<String, Int>>()
        for (line in raw.lineSequence()) {
            val trimmed = line.trim()
            if (trimmed.isEmpty() || trimmed.startsWith('#')) continue
            val tab = trimmed.indexOf('\t')
            if (tab <= 0) continue
            val word = trimmed.substring(0, tab)
            val count = trimmed.substring(tab + 1).trim().toIntOrNull() ?: continue
            if (count <= 0 || normalize(word).isEmpty()) continue
            val key = normalize(word)
            counts[key] = if (counts.containsKey(key)) {
                (counts[key]!!.first to counts[key]!!.second + count)
            } else {
                (word to count)
            }
        }
        // Cap at MAX_USER_WORDS by count — a restore file can be arbitrary.
        if (counts.size <= MAX_USER_WORDS) return counts
        return counts.values.sortedByDescending { it.second }
            .take(MAX_USER_WORDS)
            .associateByTo(LinkedHashMap()) { normalize(it.first) }
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    /** First index whose value is >= [query]; [arr] must be sorted. */
    private fun lowerBound(arr: Array<String>, query: String): Int {
        var lo = 0
        var hi = arr.size
        while (lo < hi) {
            val mid = (lo + hi) ushr 1
            if (arr[mid] < query) lo = mid + 1 else hi = mid
        }
        return lo
    }
}
